#
# Copyright (c) 2012 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
# 
# Makefile for MV7420 camera branch. 
# by liping.qian@samsung.com

ifeq ($(CONFIG_SOC_EXYNOS7420),y)
	obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS)	+= ../fimc-is2/
else
	obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS)	+= ../fimc-is/
endif

